apiVersion: v1
kind: ConfigMap
metadata:
  name: multi-config
data:
  COURSE_NAME: DevOps
  CLOUD_NAME: AWS
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-multiconfig
spec:
  containers:
  - name: web
    image: nginx
    envFrom:
    - configMapRef:
        name: multi-config
    ports:
    - name: http
      containerPort: 80
    resources:
      requests:
        cpu: "128m"
        memory: "256Mi"
      limits:
        cpu: "256m"
        memory: "512Mi"
