apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    project: roboshop
    environment: dev
spec:
  containers:
  - name: web
    image: nginx
    ports:
    - name: http
      containerPort: 80
    resources:
      requests:
        cpu: "128m"
        memory: "256Mi"
      limits:
        cpu: "256m"
        memory: "512Mi"