apiVersion: v1
kind: ConfigMap
metadata:
  name: config-demo
data:
  COURSE_NAME: DevOps
  CLOUD_NAME: AWS
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
  - name: web
    image: nginx
    env:
    - name: course
      valueFrom:
        configMapKeyRef:
          name: config-demo
          key: COURSE_NAME
    - name: cloud-provider
      valueFrom:
        configMapKeyRef:
          name: config-demo
          key: CLOUD_NAME
