apiVersion: v1
kind: Pod
metadata:
  name: multi-containers
spec:
  containers:
  - name: web1
    image: nginx
    ports:
    - name: https
      containerPort: 443
  - name: web2
    image: almalinux:8
    command: ["sleep" "95"]
    ports:
    - name: http
      containerPort: 80