apiVersion: v1
kind: Pod
metadata:
  name: resources-demo
spec:
  containers:
  - name: web
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - name: http
      containerPort: 80