apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
spec:
  type: ClusterIp
  selector:
    app: web
    environment: dev
    ports:
    - name: web-service
      port: 80
      protocol: TCP
      targetPort: web
---
apiVersion: v1
kind: Pod
metadata:
  name: web-demo
  labels:
    app: web
    environment: dev
spec:
  containers:
  - name: web
    image: nginx
    resources:
      requests:
        cpu: "126m"
        memory: "256Mi"
      limits:
        cpu: "256m"
        memory: "512Mi"
    ports:
    - name: web
      containerPort: 80