apiVersion: v1
kind: Pod
metadata:
  name: loadbalancer-web
  labels:
    app: web
    environment: dev
spec:
  containers:
  - name: web
    image: nginx
    resources:
      requests:
        cpu: "126m"
        memory: "256Mi"
      limits:
        cpu: "256m"
        memory: "512Mi"
    ports:
    - name: http-web
      containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: web
    environment: dev
  ports:
  - name: loadbalancer-port
    port: 80
    protocol: TCP
    targetPort: http-web
  