apiVersion: v1
kind: Pod
metadata:
  name: web-nodeport-service
  labels:
    app: web
    environment: dev
spec:
  containers:
  - name: web
    image: nginx
    resources:
      requests:
        cpu: "126m"
        memory: "256Mi"
      limits:
        cpu: "256m"
        memory: "512Mi"
    ports:
    - name: web
      containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: nodeport
  selector:
    app: web
    environment: dev
  ports:
  - name: web-service-port
    port: 80
    protocol: TCP
    targetPort: web
    
  