apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels: 
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      environment: dev
  template:
    metadata:
      labels:
        app: mongodb
        environment: dev
    spec:
      containers:
      - name: mongodb
        image: venkat1095/mongodb:v1
        ports:
        - name: mongodb-port
          containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: roboshop
  labels:
    project: roboshop
spec:
  type: clusterIP
  selector:
    app: mongodb
    environment: dev
  ports:
  - name: service-port
    port: 27017
    protocol: TCP
    targetPort: mongodb-port