apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-demo
  labels:
    project: roboshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
      environment: dev
  template:
    metadata:
      labels:
        app: web
        environment: dev
    spec:
      containers:
      - name: web
        image: nginx
        ports:
        - name: http-web
          containerPort: 80
        resources:
          requests:
            cpu: "126m"
            memory: "256Mi"
          limits:
            cpu: "256m"
            memory: "512Mi"